// <auto-generated />
namespace TiendaVideojuegos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agregadovistacarrito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregadovistacarrito));
        
        string IMigrationMetadata.Id
        {
            get { return "202012102123049_Agregado vista carrito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
