// <auto-generated />
namespace TiendaVideojuegos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Seañadeelclienteyelmodelocompras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seañadeelclienteyelmodelocompras));
        
        string IMigrationMetadata.Id
        {
            get { return "202012110401293_Se añade el cliente y el modelo compras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
