// <auto-generated />
namespace TiendaVideojuegos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agregadasllavesforaneas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregadasllavesforaneas));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101738577_Agregadas llaves foraneas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
